### ISSUE TITLE
Hamburger menu should be on the right hand side on mobile

### ISSUE THREAD

**Issue by CalumMackenzie-Chambers** [CalumMackenzie-Chambers/brain#5]
**Describe the bug**
On mobile the hamburger menu appears on the left next to the logo. It should really be on the right hand side

**To Reproduce**
1. Go to https://brain.mackenzie-chambers.co.uk/ on a mobile device
2. Notice that the hamberger menu is in the top left of the screen

**Expected behavior**
The menu toggle should be in the top right

**Smartphone (please complete the following information):**
 - Device: All
 - OS: All
 - Browser: All

**Additional context**
I have also been considering a moblie nav at the bottom of the screen as I find this more accessable then at the top. Since both of these issues are about the hamberger menu accessiblilty I will attempt to fix them both here providing the solution is trivial.

**Comment by dayanrr91** [comment]
Hey, if you open this repo to allow pushes will add PR to fix this issue.

**Comment by CalumMackenzie-Chambers** [comment]
> Hey, if you open this repo to allow pushes will add PR to fix this issue.

Hey, I wasn't expecting contributions to this repository so I haven't set up any contributing docs yet. Evidently I was wrong so I will get that set up now. Thanks for your contribution!
